export const getCountryList = () => {
  return [
    { ID: "AD", EnglishName: "Andorra", phone: "376" },
    {
      ID: "AE",
      EnglishName: "United Arab Emirates",
      phone: "971",
    },
    { ID: "AF", EnglishName: "Afghanistan", phone: "93" },
    {
      ID: "AG",
      EnglishName: "Antigua and Barbuda",
      phone: "1-268",
    },
    { ID: "AI", EnglishName: "Anguilla", phone: "1-264" },
    { ID: "AL", EnglishName: "Albania", phone: "355" },
    { ID: "AM", EnglishName: "Armenia", phone: "374" },
    { ID: "AO", EnglishName: "Angola", phone: "244" },
    { ID: "AQ", EnglishName: "Antarctica", phone: "672" },
    { ID: "AR", EnglishName: "Argentina", phone: "54" },
    { ID: "AS", EnglishName: "American Samoa", phone: "1-684" },
    { ID: "AT", EnglishName: "Austria", phone: "43" },
    {
      ID: "AU",
      EnglishName: "Australia",
      phone: "61",
      suggested: true,
    },
    { ID: "AW", EnglishName: "Aruba", phone: "297" },
    { ID: "AX", EnglishName: "Alland Islands", phone: "358" },
    { ID: "AZ", EnglishName: "Azerbaijan", phone: "994" },
    {
      ID: "BA",
      EnglishName: "Bosnia and Herzegovina",
      phone: "387",
    },
    { ID: "BB", EnglishName: "Barbados", phone: "1-246" },
    { ID: "BD", EnglishName: "Bangladesh", phone: "880" },
    { ID: "BE", EnglishName: "Belgium", phone: "32" },
    { ID: "BF", EnglishName: "Burkina Faso", phone: "226" },
    { ID: "BG", EnglishName: "Bulgaria", phone: "359" },
    { ID: "BH", EnglishName: "Bahrain", phone: "973" },
    { ID: "BI", EnglishName: "Burundi", phone: "257" },
    { ID: "BJ", EnglishName: "Benin", phone: "229" },
    { ID: "BL", EnglishName: "Saint Barthelemy", phone: "590" },
    { ID: "BM", EnglishName: "Bermuda", phone: "1-441" },
    { ID: "BN", EnglishName: "Brunei Darussalam", phone: "673" },
    { ID: "BO", EnglishName: "Bolivia", phone: "591" },
    { ID: "BR", EnglishName: "Brazil", phone: "55" },
    { ID: "BS", EnglishName: "Bahamas", phone: "1-242" },
    { ID: "BT", EnglishName: "Bhutan", phone: "975" },
    { ID: "BV", EnglishName: "Bouvet Island", phone: "47" },
    { ID: "BW", EnglishName: "Botswana", phone: "267" },
    { ID: "BY", EnglishName: "Belarus", phone: "375" },
    { ID: "BZ", EnglishName: "Belize", phone: "501" },
    {
      ID: "CA",
      EnglishName: "Canada",
      phone: "1",
      suggested: true,
    },
    {
      ID: "CC",
      EnglishName: "Cocos (Keeling) Islands",
      phone: "61",
    },
    {
      ID: "CD",
      EnglishName: "Congo, Democratic Republic of the",
      phone: "243",
    },
    {
      ID: "CF",
      EnglishName: "Central African Republic",
      phone: "236",
    },
    {
      ID: "CG",
      EnglishName: "Congo, Republic of the",
      phone: "242",
    },
    { ID: "CH", EnglishName: "Switzerland", phone: "41" },
    { ID: "CI", EnglishName: "Cote d'Ivoire", phone: "225" },
    { ID: "CK", EnglishName: "Cook Islands", phone: "682" },
    { ID: "CL", EnglishName: "Chile", phone: "56" },
    { ID: "CM", EnglishName: "Cameroon", phone: "237" },
    { ID: "CN", EnglishName: "China", phone: "86" },
    { ID: "CO", EnglishName: "Colombia", phone: "57" },
    { ID: "CR", EnglishName: "Costa Rica", phone: "506" },
    { ID: "CU", EnglishName: "Cuba", phone: "53" },
    { ID: "CV", EnglishName: "Cape Verde", phone: "238" },
    { ID: "CW", EnglishName: "Curacao", phone: "599" },
    { ID: "CX", EnglishName: "Christmas Island", phone: "61" },
    { ID: "CY", EnglishName: "Cyprus", phone: "357" },
    { ID: "CZ", EnglishName: "Czech Republic", phone: "420" },
    {
      ID: "DE",
      EnglishName: "Germany",
      phone: "49",
      suggested: true,
    },
    { ID: "DJ", EnglishName: "Djibouti", phone: "253" },
    { ID: "DK", EnglishName: "Denmark", phone: "45" },
    { ID: "DM", EnglishName: "Dominica", phone: "1-767" },
    {
      ID: "DO",
      EnglishName: "Dominican Republic",
      phone: "1-809",
    },
    { ID: "DZ", EnglishName: "Algeria", phone: "213" },
    { ID: "EC", EnglishName: "Ecuador", phone: "593" },
    { ID: "EE", EnglishName: "Estonia", phone: "372" },
    { ID: "EG", EnglishName: "Egypt", phone: "20" },
    { ID: "EH", EnglishName: "Western Sahara", phone: "212" },
    { ID: "ER", EnglishName: "Eritrea", phone: "291" },
    { ID: "ES", EnglishName: "Spain", phone: "34" },
    { ID: "ET", EnglishName: "Ethiopia", phone: "251" },
    { ID: "FI", EnglishName: "Finland", phone: "358" },
    { ID: "FJ", EnglishName: "Fiji", phone: "679" },
    {
      ID: "FK",
      EnglishName: "Falkland Islands (Malvinas)",
      phone: "500",
    },
    {
      ID: "FM",
      EnglishName: "Micronesia, Federated States of",
      phone: "691",
    },
    { ID: "FO", EnglishName: "Faroe Islands", phone: "298" },
    {
      ID: "FR",
      EnglishName: "France",
      phone: "33",
      suggested: true,
    },
    { ID: "GA", EnglishName: "Gabon", phone: "241" },
    { ID: "GB", EnglishName: "United Kingdom", phone: "44" },
    { ID: "GD", EnglishName: "Grenada", phone: "1-473" },
    { ID: "GE", EnglishName: "Georgia", phone: "995" },
    { ID: "GF", EnglishName: "French Guiana", phone: "594" },
    { ID: "GG", EnglishName: "Guernsey", phone: "44" },
    { ID: "GH", EnglishName: "Ghana", phone: "233" },
    { ID: "GI", EnglishName: "Gibraltar", phone: "350" },
    { ID: "GL", EnglishName: "Greenland", phone: "299" },
    { ID: "GM", EnglishName: "Gambia", phone: "220" },
    { ID: "GN", EnglishName: "Guinea", phone: "224" },
    { ID: "GP", EnglishName: "Guadeloupe", phone: "590" },
    { ID: "GQ", EnglishName: "Equatorial Guinea", phone: "240" },
    { ID: "GR", EnglishName: "Greece", phone: "30" },
    {
      ID: "GS",
      EnglishName: "South Georgia and the South Sandwich Islands",
      phone: "500",
    },
    { ID: "GT", EnglishName: "Guatemala", phone: "502" },
    { ID: "GU", EnglishName: "Guam", phone: "1-671" },
    { ID: "GW", EnglishName: "Guinea-Bissau", phone: "245" },
    { ID: "GY", EnglishName: "Guyana", phone: "592" },
    { ID: "HK", EnglishName: "Hong Kong", phone: "852" },
    {
      ID: "HM",
      EnglishName: "Heard Island and McDonald Islands",
      phone: "672",
    },
    { ID: "HN", EnglishName: "Honduras", phone: "504" },
    { ID: "HR", EnglishName: "Croatia", phone: "385" },
    { ID: "HT", EnglishName: "Haiti", phone: "509" },
    { ID: "HU", EnglishName: "Hungary", phone: "36" },
    { ID: "ID", EnglishName: "Indonesia", phone: "62" },
    { ID: "IE", EnglishName: "Ireland", phone: "353" },
    { ID: "IL", EnglishName: "Israel", phone: "972" },
    { ID: "IM", EnglishName: "Isle of Man", phone: "44" },
    { ID: "IN", EnglishName: "India", phone: "91" },
    {
      ID: "IO",
      EnglishName: "British Indian Ocean Territory",
      phone: "246",
    },
    { ID: "IQ", EnglishName: "Iraq", phone: "964" },
    {
      ID: "IR",
      EnglishName: "Iran, Islamic Republic of",
      phone: "98",
    },
    { ID: "IS", EnglishName: "Iceland", phone: "354" },
    { ID: "IT", EnglishName: "Italy", phone: "39" },
    { ID: "JE", EnglishName: "Jersey", phone: "44" },
    { ID: "JM", EnglishName: "Jamaica", phone: "1-876" },
    { ID: "JO", EnglishName: "Jordan", phone: "962" },
    {
      ID: "JP",
      EnglishName: "Japan",
      phone: "81",
      suggested: true,
    },
    { ID: "KE", EnglishName: "Kenya", phone: "254" },
    { ID: "KG", EnglishName: "Kyrgyzstan", phone: "996" },
    { ID: "KH", EnglishName: "Cambodia", phone: "855" },
    { ID: "KI", EnglishName: "Kiribati", phone: "686" },
    { ID: "KM", EnglishName: "Comoros", phone: "269" },
    {
      ID: "KN",
      EnglishName: "Saint Kitts and Nevis",
      phone: "1-869",
    },
    {
      ID: "KP",
      EnglishName: "Korea, Democratic People's Republic of",
      phone: "850",
    },
    { ID: "KR", EnglishName: "Korea, Republic of", phone: "82" },
    { ID: "KW", EnglishName: "Kuwait", phone: "965" },
    { ID: "KY", EnglishName: "Cayman Islands", phone: "1-345" },
    { ID: "KZ", EnglishName: "Kazakhstan", phone: "7" },
    {
      ID: "LA",
      EnglishName: "Lao People's Democratic Republic",
      phone: "856",
    },
    { ID: "LB", EnglishName: "Lebanon", phone: "961" },
    { ID: "LC", EnglishName: "Saint Lucia", phone: "1-758" },
    { ID: "LI", EnglishName: "Liechtenstein", phone: "423" },
    { ID: "LK", EnglishName: "Sri Lanka", phone: "94" },
    { ID: "LR", EnglishName: "Liberia", phone: "231" },
    { ID: "LS", EnglishName: "Lesotho", phone: "266" },
    { ID: "LT", EnglishName: "Lithuania", phone: "370" },
    { ID: "LU", EnglishName: "Luxembourg", phone: "352" },
    { ID: "LV", EnglishName: "Latvia", phone: "371" },
    { ID: "LY", EnglishName: "Libya", phone: "218" },
    { ID: "MA", EnglishName: "Morocco", phone: "212" },
    { ID: "MC", EnglishName: "Monaco", phone: "377" },
    {
      ID: "MD",
      EnglishName: "Moldova, Republic of",
      phone: "373",
    },
    { ID: "ME", EnglishName: "Montenegro", phone: "382" },
    {
      ID: "MF",
      EnglishName: "Saint Martin (French part)",
      phone: "590",
    },
    { ID: "MG", EnglishName: "Madagascar", phone: "261" },
    { ID: "MH", EnglishName: "Marshall Islands", phone: "692" },
    {
      ID: "MK",
      EnglishName: "Macedonia, the Former Yugoslav Republic of",
      phone: "389",
    },
    { ID: "ML", EnglishName: "Mali", phone: "223" },
    { ID: "MM", EnglishName: "Myanmar", phone: "95" },
    { ID: "MN", EnglishName: "Mongolia", phone: "976" },
    { ID: "MO", EnglishName: "Macao", phone: "853" },
    {
      ID: "MP",
      EnglishName: "Northern Mariana Islands",
      phone: "1-670",
    },
    { ID: "MQ", EnglishName: "Martinique", phone: "596" },
    { ID: "MR", EnglishName: "Mauritania", phone: "222" },
    { ID: "MS", EnglishName: "Montserrat", phone: "1-664" },
    { ID: "MT", EnglishName: "Malta", phone: "356" },
    { ID: "MU", EnglishName: "Mauritius", phone: "230" },
    { ID: "MV", EnglishName: "Maldives", phone: "960" },
    { ID: "MW", EnglishName: "Malawi", phone: "265" },
    { ID: "MX", EnglishName: "Mexico", phone: "52" },
    { ID: "MY", EnglishName: "Malaysia", phone: "60" },
    { ID: "MZ", EnglishName: "Mozambique", phone: "258" },
    { ID: "NA", EnglishName: "Namibia", phone: "264" },
    { ID: "NC", EnglishName: "New Caledonia", phone: "687" },
    { ID: "NE", EnglishName: "Niger", phone: "227" },
    { ID: "NF", EnglishName: "Norfolk Island", phone: "672" },
    { ID: "NG", EnglishName: "Nigeria", phone: "234" },
    { ID: "NI", EnglishName: "Nicaragua", phone: "505" },
    { ID: "NL", EnglishName: "Netherlands", phone: "31" },
    { ID: "NO", EnglishName: "Norway", phone: "47" },
    { ID: "NP", EnglishName: "Nepal", phone: "977" },
    { ID: "NR", EnglishName: "Nauru", phone: "674" },
    { ID: "NU", EnglishName: "Niue", phone: "683" },
    { ID: "NZ", EnglishName: "New Zealand", phone: "64" },
    { ID: "OM", EnglishName: "Oman", phone: "968" },
    { ID: "PA", EnglishName: "Panama", phone: "507" },
    { ID: "PE", EnglishName: "Peru", phone: "51" },
    { ID: "PF", EnglishName: "French Polynesia", phone: "689" },
    { ID: "PG", EnglishName: "Papua New Guinea", phone: "675" },
    { ID: "PH", EnglishName: "Philippines", phone: "63" },
    { ID: "PK", EnglishName: "Pakistan", phone: "92" },
    { ID: "PL", EnglishName: "Poland", phone: "48" },
    {
      ID: "PM",
      EnglishName: "Saint Pierre and Miquelon",
      phone: "508",
    },
    { ID: "PN", EnglishName: "Pitcairn", phone: "870" },
    { ID: "PR", EnglishName: "Puerto Rico", phone: "1" },
    {
      ID: "PS",
      EnglishName: "Palestine, State of",
      phone: "970",
    },
    { ID: "PT", EnglishName: "Portugal", phone: "351" },
    { ID: "PW", EnglishName: "Palau", phone: "680" },
    { ID: "PY", EnglishName: "Paraguay", phone: "595" },
    { ID: "QA", EnglishName: "Qatar", phone: "974" },
    { ID: "RE", EnglishName: "Reunion", phone: "262" },
    { ID: "RO", EnglishName: "Romania", phone: "40" },
    { ID: "RS", EnglishName: "Serbia", phone: "381" },
    { ID: "RU", EnglishName: "Russian Federation", phone: "7" },
    { ID: "RW", EnglishName: "Rwanda", phone: "250" },
    { ID: "SA", EnglishName: "Saudi Arabia", phone: "966" },
    { ID: "SB", EnglishName: "Solomon Islands", phone: "677" },
    { ID: "SC", EnglishName: "Seychelles", phone: "248" },
    { ID: "SD", EnglishName: "Sudan", phone: "249" },
    { ID: "SE", EnglishName: "Sweden", phone: "46" },
    { ID: "SG", EnglishName: "Singapore", phone: "65" },
    { ID: "SH", EnglishName: "Saint Helena", phone: "290" },
    { ID: "SI", EnglishName: "Slovenia", phone: "386" },
    {
      ID: "SJ",
      EnglishName: "Svalbard and Jan Mayen",
      phone: "47",
    },
    { ID: "SK", EnglishName: "Slovakia", phone: "421" },
    { ID: "SL", EnglishName: "Sierra Leone", phone: "232" },
    { ID: "SM", EnglishName: "San Marino", phone: "378" },
    { ID: "SN", EnglishName: "Senegal", phone: "221" },
    { ID: "SO", EnglishName: "Somalia", phone: "252" },
    { ID: "SR", EnglishName: "Suriname", phone: "597" },
    { ID: "SS", EnglishName: "South Sudan", phone: "211" },
    {
      ID: "ST",
      EnglishName: "Sao Tome and Principe",
      phone: "239",
    },
    { ID: "SV", EnglishName: "El Salvador", phone: "503" },
    {
      ID: "SX",
      EnglishName: "Sint Maarten (Dutch part)",
      phone: "1-721",
    },
    {
      ID: "SY",
      EnglishName: "Syrian Arab Republic",
      phone: "963",
    },
    { ID: "SZ", EnglishName: "Swaziland", phone: "268" },
    {
      ID: "TC",
      EnglishName: "Turks and Caicos Islands",
      phone: "1-649",
    },
    { ID: "TD", EnglishName: "Chad", phone: "235" },
    {
      ID: "TF",
      EnglishName: "French Southern Territories",
      phone: "262",
    },
    { ID: "TG", EnglishName: "Togo", phone: "228" },
    { ID: "TH", EnglishName: "Thailand", phone: "66" },
    { ID: "TJ", EnglishName: "Tajikistan", phone: "992" },
    { ID: "TK", EnglishName: "Tokelau", phone: "690" },
    { ID: "TL", EnglishName: "Timor-Leste", phone: "670" },
    { ID: "TM", EnglishName: "Turkmenistan", phone: "993" },
    { ID: "TN", EnglishName: "Tunisia", phone: "216" },
    { ID: "TO", EnglishName: "Tonga", phone: "676" },
    { ID: "TR", EnglishName: "Turkey", phone: "90" },
    {
      ID: "TT",
      EnglishName: "Trinidad and Tobago",
      phone: "1-868",
    },
    { ID: "TV", EnglishName: "Tuvalu", phone: "688" },
    {
      ID: "TW",
      EnglishName: "Taiwan, Republic of China",
      phone: "886",
    },
    {
      ID: "TZ",
      EnglishName: "United Republic of Tanzania",
      phone: "255",
    },
    { ID: "UA", EnglishName: "Ukraine", phone: "380" },
    { ID: "UG", EnglishName: "Uganda", phone: "256" },
    {
      ID: "US",
      EnglishName: "United States",
      phone: "1",
      suggested: true,
    },
    { ID: "UY", EnglishName: "Uruguay", phone: "598" },
    { ID: "UZ", EnglishName: "Uzbekistan", phone: "998" },
    {
      ID: "VA",
      EnglishName: "Holy See (Vatican City State)",
      phone: "379",
    },
    {
      ID: "VC",
      EnglishName: "Saint Vincent and the Grenadines",
      phone: "1-784",
    },
    { ID: "VE", EnglishName: "Venezuela", phone: "58" },
    {
      ID: "VG",
      EnglishName: "British Virgin Islands",
      phone: "1-284",
    },
    {
      ID: "VI",
      EnglishName: "US Virgin Islands",
      phone: "1-340",
    },
    { ID: "VN", EnglishName: "Vietnam", phone: "84" },
    { ID: "VU", EnglishName: "Vanuatu", phone: "678" },
    { ID: "WF", EnglishName: "Wallis and Futuna", phone: "681" },
    { ID: "WS", EnglishName: "Samoa", phone: "685" },
    { ID: "XK", EnglishName: "Kosovo", phone: "383" },
    { ID: "YE", EnglishName: "Yemen", phone: "967" },
    { ID: "YT", EnglishName: "Mayotte", phone: "262" },
    { ID: "ZA", EnglishName: "South Africa", phone: "27" },
    { ID: "ZM", EnglishName: "Zambia", phone: "260" },
    { ID: "ZW", EnglishName: "Zimbabwe", phone: "263" },
  ];
};
